version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    restart: always
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    container_name: iShariu
    depends_on:
      - db

  db:
    image: "mongo:latest"
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: shariy
      MONGO_INITDB_ROOT_PASSWORD: partiya
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
        
        

volumes:
  mongodb_data: